### ISSUE TITLE
Code Coming Soon! 

### ISSUE THREAD

**Issue by hansbase** [qianqianwang68/omnimotion#13]
I'm excited for this code to be shared. When do you think that will be?

**Comment by chopin1998** [comment]
any update?

**Comment by bulutthecat** [comment]
still waiting

**Comment by qianqianwang68** [comment]
Hi sorry about the wait, the code will be out this week

**Comment by qianqianwang68** [comment]
The code is now released. Let me know if you come across any problems when running it
