### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ShenEffort** [qianqianwang68/omnimotion#18]
Could not find a version that satisfies the requirement torchvision==0.11.0+cu111 ,Could you please check it, thanks.

**Comment by qianqianwang68** [comment]
Thank you @Ryandonofrio3! @ShenEffort Let me know if your issue is resolved. If not, could you provide your system information and Python version?

**Comment by ShenEffort** [comment]
Thank you for response. The first time I configured the environment on the windows system according to the official document, then the above error message appeared, but when I used another computer (ubnutu system) did not appear the above error, I think it is the difference of the system. Finally, I also want to ask how to reduce the training costs, because my computer only 12 g memory, and have, in accordance with the official suggest the num_pts and chunk_size modified into 1.

**Comment by ShenEffort** [comment]
> 你好，如果你在 Windows 上，我也遇到了同样的问题！为了解决这个问题，我按照以下指南卸载了 CUDA/CUDNN：
> 
> [https://medium.com/geekculture/install-cuda-and-cudnn-on-windows-linux-52d1501a8805）](https://medium.com/geekculture/install-cuda-and-cudnn-on-windows-linux-52d1501a8805)
> 
> 然后安装 pytorch 等：
> 
> https://stackoverflow.com/questions/55717751/torch-cuda-is-available-keeps-switching-to-false
> 
> 现在我运行这段代码来测试：
> 
> ` 进口火炬
> 
> 打印（火炬。**版本**）
> 
> 打印（torch.cuda.is_available（）） `

**Comment by ShenEffort** [comment]
> 你好，如果你在 Windows 上，我也遇到了同样的问题！为了解决这个问题，我按照以下指南卸载了 CUDA/CUDNN：
> 
> [https://medium.com/geekculture/install-cuda-and-cudnn-on-windows-linux-52d1501a8805）](https://medium.com/geekculture/install-cuda-and-cudnn-on-windows-linux-52d1501a8805)
> 
> 然后安装 pytorch 等：
> 
> https://stackoverflow.com/questions/55717751/torch-cuda-is-available-keeps-switching-to-false
> 
> 现在我运行这段代码来测试：
> 
> ` 进口火炬
> 
> 打印（火炬。**版本**）
> 
> 打印（torch.cuda.is_available（）） `

Thanks for reply, I have success on ubnutu system configuration
