### ISSUE TITLE
Specific weight for each sequence

### ISSUE THREAD

**Issue by xieyuser** [qianqianwang68/omnimotion#28]
It seems that every image sequence has it's own weight, look forward you to improve this repo.

**Comment by qianqianwang68** [comment]
the method we propose is a test-time optimization-based method (i.e., per-video training), so each sequence will have its own weight. Extending it to work in a generalized way is beyond the scope of this repo, but i encourage you to take a look at this line of work if you are in search of this kind of method:

https://co-tracker.github.io/
https://deepmind-tapir.github.io/
https://github.com/aharley/pips2
