### ISSUE TITLE
installing and running omnimotion with only cpu

### ISSUE THREAD

**Issue by hannahscope** [qianqianwang68/omnimotion#29]
Hello! Thank you for sharing this code - omnimotion looks really promising and I would love to test it out with some of my microscope videos. But having tried installing it, it seems that I cannot run CUDA on my computer. Is it possible to run omnimotion with cpu only?

**Comment by qianqianwang68** [comment]
Hi, unfortunately, it would be extremely slow to run on CPU. I suggest you look into this work https://co-tracker.github.io/ for your project.

**Comment by hannahscope** [comment]
Thank you for your suggestion! I will check it out :)
