### ISSUE TITLE
Dears, when will you release the code and the model?

### ISSUE THREAD

**Issue by Eternal-Br** [qianqianwang68/omnimotion#3]
Dears, when will you release the code and the model?

**Comment by yhyu13** [comment]
Game changer!

**Comment by qianqianwang68** [comment]
Thank you for your interest. We're still working out when it will be ready to be released, but we'll keep you posted once we have a definitive timeline.

**Comment by ernestchu** [comment]
Can we have a sneak peek of its efficiency? Like how many seconds it needs for optimizing one frame in average (sec/frame).

**Comment by zacharyfmarion** [comment]
@qianqianwang68 any update on the timeline? Would be great even if it was a ballpark - like 2 weeks, 2 months, half a year. Trying to figure out whether to wait for this to work on a project.

**Comment by qianqianwang68** [comment]
Hi, it will definitely be before the conference, but we aim to have it even sooner than that, hopefully by August.

**Comment by wuzirui** [comment]
Hi @qianqianwang68, thank you for the great work!  Will the supplementary materials be released with the code or maybe earlier? Looking forward to the technical details~

**Comment by vrk7** [comment]
Hi @qianqianwang68, will the code be released soon?
