### ISSUE TITLE
how to use args.distributed

### ISSUE THREAD

**Issue by fangxy100** [qianqianwang68/omnimotion#30]

**Comment by qianqianwang68** [comment]
Hi, to use distributed training, you can try `python -m torch.distributed.launch --nproc_per_node={NUM_GPUs} train.py ....`. The total number of points trained equals NUM_GPUs * args.num_pts, which means that args.num_pts can be reduced to 1/NUM_GPUs of the total number of points desired. The distributed training option is less thoroughly tested so please let me know if you encounter any problems.

**Comment by nargenziano** [comment]
How about the batch size (i.e., args.num_pairs?
