### ISSUE TITLE
some problem in Computing and processing flow

### ISSUE THREAD

**Issue by jdyjjj** [qianqianwang68/omnimotion#32]
Congratulations, thank you very much for your amazing work.
when I want to compute and process flow, I meet some problem. Here is the command I ran:
```
python main_processing.py --data_dir /home/omnimotion/data/01_0 --chain
```
This is the error message:
```
Traceback (most recent call last):
  File "exhaustive_raft.py", line 18, in <module>
    from raft import RAFT
ModuleNotFoundError: No module named 'raft'
Traceback (most recent call last):
  File "extract_dino_features.py", line 26, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
flitering raft optical flow for /home/omnimotion/data/01_0....
  0%|                                                                       | 0/54056 [00:00<?, ?it/s]Traceback (most recent call last):
  File "filter_raft.py", line 125, in <module>
    run_filtering(args)
  File "filter_raft.py", line 50, in run_filtering
    features = [torch.from_numpy(np.load(os.path.join(scene_dir, 'features', feature_name,
  File "filter_raft.py", line 50, in <listcomp>
    features = [torch.from_numpy(np.load(os.path.join(scene_dir, 'features', feature_name,
  File "/home/anaconda3/envs/omnimotion/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/omnimotion/data/01_0/features/dino/000.jpg.npy
```

This is the structure of the folder (/home/omnimotion/data/01_0 )：
![image](https://github.com/qianqianwang68/omnimotion/assets/73057174/35d8d46d-bfa1-45aa-8688-7aa3fd0f7969)
Thanks very much

**Comment by ys830** [comment]
I'd like to ask a question. Is it always necessary to have a `/sequence_name/mask` file when using custom data? I couldn't seem to find any use of the file `/mask` in the preprocessing code I was looking at.

**Comment by qianqianwang68** [comment]
Hi @jdyjjj can you check if the RAFT and dino folder under the preprocessing folder is empty? Make sure that you also clone the submodules when you clone the repo (i.e., you should use `git clone --recurse-submodules https://github.com/qianqianwang68/omnimotion/`).

@ys830 the `sequence_name/mask` is not required for preprocessing or training. It is only needed for visualization purposes.
