### ISSUE TITLE
Can multiple data be trained?

### ISSUE THREAD

**Issue by zhiyangxiao** [qianqianwang68/omnimotion#33]
I found that the training operation in the introduction can only train a single video sequence, I want to batch video sequence sequence how to operate? Put all the data in the same path? eg: bear/color, butterfly/color to bear_butterfly/color? Eg: Bear /color, butterfly/color to bear_butterfly/color? like this?

**Comment by zhiyangxiao** [comment]
And how do I implement using trained weight files to test other data?

**Comment by qianqianwang68** [comment]
Hi just to be clear, this method is a per-video optimization-based method, so it would only make sense to train on a single video sequence and then do inference on the same video sequence.
