### ISSUE TITLE
How to accelerate training speed?

### ISSUE THREAD

**Issue by jdyjjj** [qianqianwang68/omnimotion#38]
I have a lot of videos to process, so I would like to inquire about how to speed up the training? Reducing a certain level of performance is acceptable. Thank you a lot!

**Comment by qianqianwang68** [comment]
Thank you for your question. You may consider reducing the number of samples on a ray (`--num_samples_ray`), setting `--use_affine` to False, or downsampling your videos to smaller resolutions. 

Alternatively, depending on the specific tasks you are thinking about, other works might be useful too. You may consider feedforward approaches for dense and long-range tracking that don't require per-video optimization and thus are much faster, like TAPIR (https://deepmind-tapir.github.io/) and CoTracker (https://co-tracker.github.io/)
