### ISSUE TITLE
Will the model weights and testing code be open-sourced

### ISSUE THREAD

**Issue by JingruiYu** [qianqianwang68/omnimotion#49]
Hello,

I recently came across your project and I must say, it's an amazing piece of work. I was wondering if there are any plans to release the model weights and testing code as open source. This would be extremely helpful for those of us who would like to test the model's capabilities directly. With the weights and testing code available, we could simply input a video and see the results without having to train the model ourselves.

Thank you for your hard work and I look forward to your response.

**Comment by qianqianwang68** [comment]
Hi, could you refer to this answer? https://github.com/qianqianwang68/omnimotion/issues/37#issuecomment-1765825949. I'm sorry things are a bit disorganized. I will try to clean things up once I have some cycles. But I'd like to make it clear that this method is a per-video optimization-based method, which means that given a new input video, one would have to optimize on that video anyways to see the results.
