### ISSUE TITLE
How to create demo video

### ISSUE THREAD

**Issue by tengyu-liu** [qianqianwang68/omnimotion#8]
Again, congratulations, and thank you for the great work! 

I'm also curious about how you created the demo videos, where the tracking trajectories seem consistent in the 3D canonical frame and move as the camera moves. This indicates that OmniMotion has a good understanding of the camera motion. However, the paper suggests that the camera motion is entangled with object motion, making it difficult to render the demo videos unless I misunderstood something. 

Please correct my mistakes. Thank you very much.

**Comment by qianqianwang68** [comment]
Hi Tengyu,

Thank you for your question. Your observation is correct! To make the tracks in the demo videos more visually intuitive, we subtract the camera motion, which is simply implemented as subtracting the median pixel motion of the background regions. Note that this operation is just for visualization purposes, camera motion and object motion are still entangled in the underlying representation.

**Comment by tengyu-liu** [comment]
Thank you very much for the clear explanation! All my questions are addressed.
